Update cost.py to include claude-v1.3-100k (#31)
Fix the error caused by running `./gpt.py --model claude-v1.3-100k` :

```
KeyError: 'claude-v1.3-100k'
An uncaught exception occurred. Please report this issue on GitHub.
Traceback (most recent call last):
  File "gpt-cli/./gpt.py", line 233, in <module>
    main()
...
    PRICE_PER_TOKEN[model]["prompt"] * num_tokens_prompt
KeyError: 'claude-v1.3-100k'
```