Fix AttributeError in debug mode by renaming logging.py (#82)
Debugging the project in VSCode and Neovim using nvim-dap, triggered an
AttributeError ("AttributeError: partially initialized module 'logging'
has no attribute 'getLogger' (most likely due to a circular import)")
due to the local file logging.py shadowing the standard Python logging
module. The error occurred only while debugging.

Changes made:
- Renamed logging.py to logging_utils.py  
- Updated the import logging_utils statement

Co-authored-by: fs <fs@fs>